listen:
  port: "8096"

cachedir: /tmp/jellofin-img-cache
logfile: stdout

database:
  sqlite:
    filename: /tmp/jellofin-test.db

jellyfin:
  servername: jellofin-rs-test
  autoregister: true

collections:
  - name: Test Movies
    type: movies
    directory: /tmp/test-movies
